**Python program for multiple-choice questions using loops and if-elif-else conditions. You can modify the questions list to add your own questions.**

In [4]:
# Define a list of dictionaries, where each dictionary represents a question
questions = [
    {
        "question": "What is the capital of Pakistan?",
        "options": ["A) Berlin", "B) Madrid", "C) Islamabad", "D) Rome"],
        "answer": "C"
    },
    {
        "question": "Which planet is known as the Red Planet?",
        "options": ["A) Earth", "B) Mars", "C) Jupiter", "D) Venus"],
        "answer": "B"
    },
    {
        "question": "What is 2 + 2?",
        "options": ["A) 3", "B) 4", "C) 5", "D) 6"],
        "answer": "B"
    }
]

The input validation occurs in the else block of the if-elif-else statement. After the user enters their answer, the code checks if the user_answer matches the q['answer'] (correct) or if it's one of the valid options ('A', 'B', 'C', 'D') but incorrect. If neither of these conditions is met, it means the user's input was not a valid option, and the else block is executed:

    else:
        print("Invalid input. Please enter A, B, C, or D.")
This prints an error message, informing the user that their input was not valid. However, it currently doesn't prompt the user to re-enter their answer for the same question; it simply moves on to the next question.

In [5]:
# Initialize score
score = 0

print("Welcome to the Python Quiz!")
print("-------------------------")

# Loop through each question
for i, q in enumerate(questions):
    print(f"\nQuestion {i + 1}: {q['question']}")
    for option in q['options']:
        print(option)

    user_answer = input("Enter your answer (A, B, C, or D): ").strip().upper()

    # Check if the answer is correct using if-elif-else
    if user_answer == q['answer']:
        print("Correct!")
        score += 1
    elif user_answer in ["A", "B", "C", "D"]:
        print(f"Incorrect. The correct answer was {q['answer']}.")
    else:
        print("Invalid input. Please enter A, B, C, or D.")

print("\n-------------------------")
print(f"Quiz finished! Your final score is {score} out of {len(questions)}.")

Welcome to the Python Quiz!
-------------------------

Question 1: What is the capital of Pakistan?
A) Berlin
B) Madrid
C) Islamabad
D) Rome
Enter your answer (A, B, C, or D): C
Correct!

Question 2: Which planet is known as the Red Planet?
A) Earth
B) Mars
C) Jupiter
D) Venus
Enter your answer (A, B, C, or D): B
Correct!

Question 3: What is 2 + 2?
A) 3
B) 4
C) 5
D) 6
Enter your answer (A, B, C, or D): B
Correct!

-------------------------
Quiz finished! Your final score is 3 out of 3.


In [15]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

def display_inventory():
    print("\n--- Current Inventory ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def sell_item():
    item_name = input("Enter item name to sell: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to sell: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    inventory[item_name]["stock"] -= quantity
                    total_cost = quantity * inventory[item_name]["price"]
                    print(f"Sold {quantity} {item_name}(s) for ${total_cost:.2f}.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def purchase_item():
    item_name = input("Enter item name to purchase (restock): ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to purchase: "))
            if quantity > 0:
                inventory[item_name]["stock"] += quantity
                total_cost = quantity * inventory[item_name]["price"]
                print(f"Purchased {quantity} {item_name}(s) for ${total_cost:.2f}. Stock updated.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        # Allow adding new items for simplicity
        print("Item not found. You can add it, but for this example, we'll only restock existing items.")
        # For a more complex system, you'd prompt for price and add new entry


print("Welcome to the Grocery Store Inventory System!")

while True:
    print("\nWhat would you like to do?")
    print("1. View Inventory")
    print("2. Sell Item")
    print("3. Purchase Item (Restock)")
    print("4. Exit")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        display_inventory()
    elif choice == '2':
        sell_item()
    elif choice == '3':
        purchase_item()
    elif choice == '4':
        print("Exiting the system. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 4.")


Welcome to the Grocery Store Inventory System!

What would you like to do?
1. View Inventory
2. Sell Item
3. Purchase Item (Restock)
4. Exit
Enter your choice (1-4): 4
Exiting the system. Goodbye!


# Task
Convert the existing inventory management system into an interactive grocery shopping program by implementing the following features: initialize an empty `shopping_cart` dictionary; modify `display_inventory` to show available items, prices, and stock; add a function to `add_to_cart` which prompts the user for an item and quantity, validates stock, and adds to `shopping_cart`; create a function to `view_cart` showing items, quantities, prices, and a subtotal; develop a `checkout` function to calculate the total bill, update `inventory` stock, and clear the `shopping_cart`; adjust the main `while True` loop and menu to include options for 'View Groceries', 'Add to Cart', 'View Cart', 'Checkout', and 'Exit'. Finally, provide a summary of the new grocery shopping program and how users can interact with it.

## Initialize Shopping Cart

### Subtask:
Create an empty dictionary to store items and quantities that the user adds to their shopping cart.


**Reasoning**:
Declare a new global variable named `shopping_cart` and initialize it as an empty dictionary to store items and quantities.



In [8]:
shopping_cart = {}
print("Shopping cart initialized as an empty dictionary.")

Shopping cart initialized as an empty dictionary.


## Display Available Groceries

### Subtask:
Modify the existing `display_inventory` function to show the available grocery items along with their prices and current stock to the user.


**Reasoning**:
The subtask requires modifying the `display_inventory` function to update its header. I will replace the existing function with the modified version.



In [9]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def sell_item():
    item_name = input("Enter item name to sell: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to sell: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    inventory[item_name]["stock"] -= quantity
                    total_cost = quantity * inventory[item_name]["price"]
                    print(f"Sold {quantity} {item_name}(s) for ${total_cost:.2f}.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def purchase_item():
    item_name = input("Enter item name to purchase (restock): ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to purchase: "))
            if quantity > 0:
                inventory[item_name]["stock"] += quantity
                total_cost = quantity * inventory[item_name]["price"]
                print(f"Purchased {quantity} {item_name}(s) for ${total_cost:.2f}. Stock updated.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        # Allow adding new items for simplicity
        print("Item not found. You can add it, but for this example, we'll only restock existing items.")
        # For a more complex system, you'd prompt for price and add new entry


print("Welcome to the Grocery Store Inventory System!")

while True:
    print("\nWhat would you like to do?")
    print("1. View Inventory")
    print("2. Sell Item")
    print("3. Purchase Item (Restock)")
    print("4. Exit")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        display_inventory()
    elif choice == '2':
        sell_item()
    elif choice == '3':
        purchase_item()
    elif choice == '4':
        print("Exiting the system. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 4.")

Welcome to the Grocery Store Inventory System!

What would you like to do?
1. View Inventory
2. Sell Item
3. Purchase Item (Restock)
4. Exit
Enter your choice (1-4): 3
Enter item name to purchase (restock): apple
Enter quantity of apple to purchase: 45
Purchased 45 apple(s) for $22.50. Stock updated.

What would you like to do?
1. View Inventory
2. Sell Item
3. Purchase Item (Restock)
4. Exit
Enter your choice (1-4): 4
Exiting the system. Goodbye!


**Reasoning**:
The next step is to create the `add_to_cart` function, which will allow users to select items and quantities to add to their `shopping_cart` after validating against available `inventory` stock. This function needs to be defined within the existing script context.



In [10]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

shopping_cart = {}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def add_to_cart():
    item_name = input("Enter item name to add to cart: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to add: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    shopping_cart[item_name] = shopping_cart.get(item_name, 0) + quantity
                    print(f"Added {quantity} {item_name}(s) to your cart.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")


# The main loop and other functions will be updated in subsequent steps


## View Shopping Cart

### Subtask:
Create a function named `view_cart` that displays all items currently in the `shopping_cart`, including their quantities, individual prices, and calculates a subtotal for the items in the cart.

#### Instructions:
1. Define a new function called `view_cart`.
2. Inside `view_cart`, iterate through the `shopping_cart`.
3. For each item in the cart, retrieve its price from the `inventory`.
4. Display the item name, quantity, price per unit, and the total cost for that item (quantity * price).
5. Calculate and display a grand total for all items in the `shopping_cart`.

## View Shopping Cart

### Subtask:
Create a function named `view_cart` that displays all items currently in the `shopping_cart`, including their quantities, individual prices, and calculates a subtotal for the items in the cart.

#### Instructions:
1. Define a new function called `view_cart`.
2. Inside `view_cart`, iterate through the `shopping_cart`.
3. For each item in the cart, retrieve its price from the `inventory`.
4. Display the item name, quantity, price per unit, and the total cost for that item (quantity * price).
5. Calculate and display a grand total for all items in the `shopping_cart`.

**Reasoning**:
Now that the subtask for `view_cart` is outlined, I will provide the Python code to implement this function, which will display the contents of the shopping cart and calculate the total cost.



In [11]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

shopping_cart = {}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def add_to_cart():
    item_name = input("Enter item name to add to cart: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to add: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    shopping_cart[item_name] = shopping_cart.get(item_name, 0) + quantity
                    print(f"Added {quantity} {item_name}(s) to your cart.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def view_cart():
    print("\n--- Your Shopping Cart ---")
    if not shopping_cart:
        print("Your cart is empty.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        print(f"{item.capitalize()}: {quantity} x ${price:.2f} = ${item_total:.2f}")
    print("--------------------------")
    print(f"Subtotal: ${total_bill:.2f}")
    print("--------------------------")

# The main loop and other functions will be updated in subsequent steps


**Reasoning**:
The subtask for creating the `view_cart` function has been outlined. Now, I will provide the Python code to implement this function, which will display the contents of the shopping cart and calculate the total cost, by adding it to the existing code.



In [12]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

shopping_cart = {}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def add_to_cart():
    item_name = input("Enter item name to add to cart: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to add: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    shopping_cart[item_name] = shopping_cart.get(item_name, 0) + quantity
                    print(f"Added {quantity} {item_name}(s) to your cart.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def view_cart():
    print("\n--- Your Shopping Cart ---")
    if not shopping_cart:
        print("Your cart is empty.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        print(f"{item.capitalize()}: {quantity} x ${price:.2f} = ${item_total:.2f}")
    print("--------------------------")
    print(f"Subtotal: ${total_bill:.2f}")
    print("--------------------------")

# The main loop and other functions will be updated in subsequent steps


## Checkout Process

### Subtask:
Develop a function to finalize the shopping experience. It will calculate the total bill, update the main `inventory` by deducting the purchased items from stock, and then clear the user's `shopping_cart`.


#### Reasoning:
The `checkout` function is crucial for finalizing the transaction. It ensures that the total cost of items in the `shopping_cart` is calculated, the `inventory` stock is accurately updated to reflect the purchased items, and the `shopping_cart` is cleared for the next customer. This function brings together the core logic of a grocery shopping system.

**Reasoning**:
I will now provide the Python code to implement the `checkout` function, including all the existing functions and global variables to ensure the code is complete and executable in one block, as per the detailed instructions of the subtask.



In [13]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

shopping_cart = {}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def add_to_cart():
    item_name = input("Enter item name to add to cart: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to add: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    shopping_cart[item_name] = shopping_cart.get(item_name, 0) + quantity
                    print(f"Added {quantity} {item_name}(s) to your cart.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def view_cart():
    print("\n--- Your Shopping Cart ---")
    if not shopping_cart:
        print("Your cart is empty.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        print(f"{item.capitalize()}: {quantity} x ${price:.2f} = ${item_total:.2f}")
    print("--------------------------")
    print(f"Subtotal: ${total_bill:.2f}")
    print("--------------------------")

def checkout():
    print("\n--- Checking Out ---")
    if not shopping_cart:
        print("Your cart is empty. Nothing to checkout.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        inventory[item]["stock"] -= quantity  # Deduct from stock

    print(f"Your total bill is: ${total_bill:.2f}")
    shopping_cart.clear()  # Clear the shopping cart
    print("Purchase complete! Your cart has been cleared.")
    print("--------------------")

# The main loop will be updated in the next step

## Update Main Program Loop and Menu

### Subtask:
Adjust the main `while True` loop to present a new menu with options for 'View Groceries', 'Add to Cart', 'View Cart', 'Checkout', and 'Exit'. Implement the logic to call the corresponding functions based on the user's choice.

**Reasoning**:
Now I will provide the Python code to update the main `while True` loop and menu, replacing the old inventory management options with the new grocery shopping functionalities and ensuring all previously defined functions and variables are included for a complete, runnable script.



In [14]:
inventory = {
    "apple": {"price": 0.50, "stock": 100},
    "banana": {"price": 0.30, "stock": 150},
    "milk": {"price": 2.00, "stock": 50},
    "bread": {"price": 2.50, "stock": 30}
}

shopping_cart = {}

def display_inventory():
    print("\n--- Available Groceries ---")
    for item, details in inventory.items():
        print(f"{item.capitalize()}: Stock = {details['stock']}, Price = ${details['price']:.2f}")
    print("-------------------------")

def add_to_cart():
    item_name = input("Enter item name to add to cart: ").lower()
    if item_name in inventory:
        try:
            quantity = int(input(f"Enter quantity of {item_name} to add: "))
            if quantity > 0:
                if inventory[item_name]["stock"] >= quantity:
                    shopping_cart[item_name] = shopping_cart.get(item_name, 0) + quantity
                    print(f"Added {quantity} {item_name}(s) to your cart.")
                else:
                    print(f"Insufficient stock. Only {inventory[item_name]['stock']} {item_name}(s) available.")
            else:
                print("Quantity must be greater than zero.")
        except ValueError:
            print("Invalid quantity. Please enter a number.")
    else:
        print("Item not found in inventory.")

def view_cart():
    print("\n--- Your Shopping Cart ---")
    if not shopping_cart:
        print("Your cart is empty.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        print(f"{item.capitalize()}: {quantity} x ${price:.2f} = ${item_total:.2f}")
    print("--------------------------")
    print(f"Subtotal: ${total_bill:.2f}")
    print("--------------------------")

def checkout():
    print("\n--- Checking Out ---")
    if not shopping_cart:
        print("Your cart is empty. Nothing to checkout.")
        return

    total_bill = 0
    for item, quantity in shopping_cart.items():
        price = inventory[item]["price"]
        item_total = quantity * price
        total_bill += item_total
        inventory[item]["stock"] -= quantity  # Deduct from stock

    print(f"Your total bill is: ${total_bill:.2f}")
    shopping_cart.clear()  # Clear the shopping cart
    print("Purchase complete! Your cart has been cleared.")
    print("--------------------")

print("Welcome to the Grocery Shopping System!")

while True:
    print("\nWhat would you like to do?")
    print("1. View Groceries")
    print("2. Add to Cart")
    print("3. View Cart")
    print("4. Checkout")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ")

    if choice == '1':
        display_inventory()
    elif choice == '2':
        add_to_cart()
    elif choice == '3':
        view_cart()
    elif choice == '4':
        checkout()
    elif choice == '5':
        print("Exiting the system. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 5.")


Welcome to the Grocery Shopping System!

What would you like to do?
1. View Groceries
2. Add to Cart
3. View Cart
4. Checkout
5. Exit
Enter your choice (1-5): 1

--- Available Groceries ---
Apple: Stock = 100, Price = $0.50
Banana: Stock = 150, Price = $0.30
Milk: Stock = 50, Price = $2.00
Bread: Stock = 30, Price = $2.50
-------------------------

What would you like to do?
1. View Groceries
2. Add to Cart
3. View Cart
4. Checkout
5. Exit
Enter your choice (1-5): 2
Enter item name to add to cart: apple
Enter quantity of apple to add: 52
Added 52 apple(s) to your cart.

What would you like to do?
1. View Groceries
2. Add to Cart
3. View Cart
4. Checkout
5. Exit
Enter your choice (1-5): 2
Enter item name to add to cart: bread
Enter quantity of bread to add: 25
Added 25 bread(s) to your cart.

What would you like to do?
1. View Groceries
2. Add to Cart
3. View Cart
4. Checkout
5. Exit
Enter your choice (1-5): 5
Exiting the system. Goodbye!


## Summary of the New Grocery Shopping Program

This interactive grocery shopping program allows users to:

1.  **View Groceries**: See all available items, their current stock, and prices.
2.  **Add to Cart**: Select items and quantities to add to their personal shopping cart. The program validates against available stock.
3.  **View Cart**: Inspect the contents of their shopping cart, including item quantities, individual prices, and a subtotal.
4.  **Checkout**: Finalize their purchase. This action calculates the total bill, updates the main inventory by deducting purchased items from stock, and then clears the shopping cart.
5.  **Exit**: Quit the program.

### How to Interact:
Users are presented with a menu of options (1-5). They need to enter the number corresponding to their desired action. For 'Add to Cart', they will be prompted for the item name and quantity. The program provides feedback on successful actions, insufficient stock, or invalid inputs, ensuring a guided shopping experience.

## Summary of the New Grocery Shopping Program

This interactive grocery shopping program allows users to:

1.  **View Groceries**: See all available items, their current stock, and prices.
2.  **Add to Cart**: Select items and quantities to add to their personal shopping cart. The program validates against available stock.
3.  **View Cart**: Inspect the contents of their shopping cart, including item quantities, individual prices, and a subtotal.
4.  **Checkout**: Finalize their purchase. This action calculates the total bill, updates the main inventory by deducting purchased items from stock, and then clears the shopping cart.
5.  **Exit**: Quit the program.

### How to Interact:
Users are presented with a menu of options (1-5). They need to enter the number corresponding to their desired action. For 'Add to Cart', they will be prompted for the item name and quantity. The program provides feedback on successful actions, insufficient stock, or invalid inputs, ensuring a guided shopping experience.

## Final Task

### Subtask:
Provide a summary of the grocery shopping program, explaining how users can interact with it and its new features.


## Summary:

### Q&A
The grocery shopping program is an interactive system that allows users to manage their shopping experience from viewing available items to checking out.

Users can interact with the program through a menu with the following options:
1.  **View Groceries**: Displays a list of all available items in the inventory, along with their current stock levels and prices.
2.  **Add to Cart**: Prompts the user to enter an item name and quantity to add to their `shopping_cart`. The program validates if the item is available and if there is sufficient stock before adding it.
3.  **View Cart**: Shows all items currently in the user's `shopping_cart`, including the quantity of each item, its individual price, and the total cost for that specific item. It also calculates and displays a subtotal for all items in the cart.
4.  **Checkout**: Finalizes the purchase. This function calculates the total bill for all items in the cart, deducts the purchased quantities from the main `inventory` stock, and then clears the `shopping_cart`.
5.  **Exit**: Terminates the program.

Users are guided through the process by entering a number corresponding to their desired action and responding to prompts for item names and quantities. The system provides feedback on actions, such as successful additions, insufficient stock, or invalid inputs.

### Data Analysis Key Findings
*   An empty `shopping_cart` dictionary was successfully initialized to store user selections.
*   The `display_inventory` function was enhanced to present available grocery items, their prices (e.g., Apple: \$0.50, Banana: \$0.30, Milk: \$2.00, Bread: \$2.50), and current stock levels.
*   A `add_to_cart` function was implemented, enabling users to add specified quantities of items to their `shopping_cart` after validating against available `inventory` stock.
*   A `view_cart` function was created to display items, quantities, and individual prices in the `shopping_cart`, calculating a subtotal for the cart contents.
*   A `checkout` function was developed to calculate the final bill, deduct purchased quantities from the `inventory`'s stock, and clear the `shopping_cart`.
*   The main program loop was updated to include a new interactive menu with options for 'View Groceries', 'Add to Cart', 'View Cart', 'Checkout', and 'Exit', linking to the corresponding functions.

### Insights or Next Steps
*   The system now offers a complete, basic e-commerce flow for grocery shopping, from browsing to checkout, enhancing user experience compared to a simple inventory management system.
*   Consider adding error handling for invalid item names in `add_to_cart` to offer suggestions or a list of available items for a more user-friendly experience.
