Date: 20-January-2026

### Instructor: Ambreen Abdul Raheem
### Professional Power BI Data Analyst And AI Agent Developer (Upwork Freelancer)
#### Topic: "if, elif & else statements"
#### Examples for more practice

**Example # 01:** First, let's create a dictionary of grocery items and their prices.

In [8]:
grocery_prices = {
    'Apples': 150.0,
    'Milk': 220.0,
    'Bread': 225.0,
    'Eggs': 400.0,
    'Cheese': 350.0,
    'Yogurt': 175.0
}

print("Grocery Prices Dictionary:")
print(grocery_prices)

Grocery Prices Dictionary:
{'Apples': 150.0, 'Milk': 220.0, 'Bread': 225.0, 'Eggs': 400.0, 'Cheese': 350.0, 'Yogurt': 175.0}


**Convert the `grocery_prices` dictionary to a pandas DataFrame**

In [46]:
import pandas as pd

# Convert the grocery_prices dictionary to a pandas DataFrame
grocery_df = pd.DataFrame(list(grocery_prices.items()), columns=['Item', 'Price'])

print("Grocery Prices DataFrame:")
display(grocery_df)

Grocery Prices DataFrame:


Item  Price
0  Apples  150.0
1    Milk  220.0
2   Bread  225.0
3    Eggs  400.0
4  Cheese  350.0
5  Yogurt  175.0

Now, let's write a Python code with an input variable and `if-elif-else` statements to check the price of a grocery item. We'll categorize prices as 'Expensive', 'Moderate', or 'Cheap' based on a few thresholds.

In [12]:
expensive_threshold = 400.0
moderate_threshold = 200.0

# Get grocery item name as input
item_name = input("Enter a grocery item to check its price: ")

# Check if the item exists in the dictionary
if item_name in grocery_prices:
    price = grocery_prices[item_name]
    print(f"\nThe price of {item_name} is: Rs{price:.2f}")

    # Apply if-elif-else statement
    if price >= expensive_threshold:
        print(f"{item_name} is considered expensive.")
    elif price >= moderate_threshold:
        print(f"{item_name} has a moderate price.")
    else:
        print(f"{item_name} is relatively cheap.")
else:
    print(f"\nError: Item '{item_name}' not found in the grocery list.")

Enter a grocery item to check its price: Yogurt

The price of Yogurt is: Rs175.00
Yogurt is relatively cheap.


**Example # 02:** First, let's create a dictionary of students and their marks.

In [3]:
student_marks = {
    'Ali': 85,
    'Saad': 45,
    'Murad Ahmed': 92,
    'Rahim': 60,
    'Ehsan': 38
}

print("Student Marks Dictionary:")
print(student_marks)

Student Marks Dictionary:
{'Ali': 85, 'Saad': 45, 'Murad Ahmed': 92, 'Rahim': 60, 'Ehsan': 38}


Now, let's write a Python code with an input variable and `if-elif-else` statements to check a student's performance based on their mark. We'll set a passing mark of 50.

In [4]:
passing_mark = 50

# Get student name as input
student_name = input("Enter student's name to check their mark: ")

# Check if the student exists in the dictionary
if student_name in student_marks:
    mark = student_marks[student_name]
    print(f"\n{student_name}'s mark: {mark}")

    # Apply if-elif-else statement
    if mark >= passing_mark:
        print(f"{student_name} has passed! Congratulations!")
    elif mark >= passing_mark - 10: # Example for a 'needs improvement' category
        print(f"{student_name} is close to passing. They need to improve.")
    else:
        print(f"{student_name} has failed. They need to study harder.")
else:
    print(f"\nError: Student '{student_name}' not found in the dictionary.")

Enter student's name to check their mark: Ehsan

Ehsan's mark: 38
Ehsan has failed. They need to study harder.


# Task # 01
Create a student grading system in Python that uses a nested dictionary to store student names, subjects, and marks. The system should define clear grading thresholds, allow the user to input a student's name and a specific subject, and then calculate and display the grade for that individual subject. Additionally, it must compute and present the student's overall percentage and corresponding overall grade across all their subjects. Finally, provide a summary of both the individual subject grade and the overall grade.

## Create Student Subject Marks Dictionary

### Subtask:
Define a Python dictionary to store student names, their subjects, and marks for each subject. This will be a nested dictionary structure.


**Reasoning**:
To define a Python dictionary named `student_grades` with a nested structure of student names, subjects, and marks, and then print it to verify its content, a code block is the appropriate command.



In [36]:
student_grades = {
    'Alice': {
        'Math': 90,
        'Science': 85,
        'History': 78
    },
    'Bob': {
        'Math': 75,
        'Science': 88,
        'History': 92
    },
    'Charlie': {
        'Math': 65,
        'Science': 70,
        'History': 80
    }
}

print("Student Grades Dictionary:")
print(student_grades)

Student Grades Dictionary:
{'Alice': {'Math': 90, 'Science': 85, 'History': 78}, 'Bob': {'Math': 75, 'Science': 88, 'History': 92}, 'Charlie': {'Math': 65, 'Science': 70, 'History': 80}}


In [37]:
student_name_input_new = input("Enter student name to view grades: ")

print(f"\nStudent Grades for {student_name_input_new}:")

if student_name_input_new in student_grades:
    print(student_grades[student_name_input_new])
else:
    print(f"Student '{student_name_input_new}' not found.")

Enter student name to view grades: Bob

Student Grades for Bob:
{'Math': 75, 'Science': 88, 'History': 92}


## Define Grading

### Subtask:
Establish the numerical thresholds for each grade category (A+, A, B, C, D) based on common academic standards, which will be used for both individual subject grades and overall grades.


**Reasoning**:
To establish the numerical for each grade category as instructed, I will define Python variables with appropriate numerical values representing the minimum percentage for each grade.



In [38]:
grade_aplus= 90
grade_a = 80
grade_b= 70
grade_c= 60
grade_d= 50

print(f"Grade A+: {grade_aplus}%")
print(f"Grade A: {grade_a}%")
print(f"Grade B: {grade_b}%")
print(f"Grade C: {grade_c}%")
print(f"Grade D: {grade_d}%")

Grade A+: 90%
Grade A: 80%
Grade B: 70%
Grade C: 60%
Grade D: 50%


## Get User Input for Student and Subject

### Subtask:
Prompt the user to enter the student's name and the specific subject for which they want to check the mark and calculate the grade.


**Reasoning**:
To prompt the user for student name and subject, store the inputs, and print them for verification, a code block with input statements and print statements is required.



In [39]:
student_name_input = input("Enter the student's name: ")
subject_name_input = input("Enter the subject name: ")

print(f"You entered student: {student_name_input}")
print(f"You entered subject: {subject_name_input}")

Enter the student's name: Bob
Enter the subject name: Math
You entered student: Bob
You entered subject: Math


## Calculate and Display Grade for Individual Subject

### Subtask:
Retrieve the mark for the specified student and subject from the dictionary. Use `if-elif-else` statements to determine the corresponding grade (A+, A, B, C, or D) based on the defined thresholds and display the result for the individual subject.


**Reasoning**:
To implement the logic for retrieving the individual subject mark and determining its grade, I will use a code block with conditional statements (if-elif-else) based on the previously defined `student_grades` dictionary, user inputs (`student_name_input`, `subject_name_input`), and grading thresholds.



In [40]:
if student_name_input in student_grades:
    if subject_name_input in student_grades[student_name_input]:
        subject_mark = student_grades[student_name_input][subject_name_input]
        individual_grade = ''

        if subject_mark >= grade_aplus:
            individual_grade = 'A+'
        elif subject_mark >= grade_a:
            individual_grade = 'A'
        elif subject_mark >= grade_b:
            individual_grade = 'B'
        elif subject_mark >= grade_c:
            individual_grade = 'C'
        elif subject_mark >= grade_d:
            individual_grade = 'D'
        else:
            individual_grade = 'F'

        print(f"\n--- Individual Subject Grade ---")
        print(f"Student: {student_name_input}")
        print(f"Subject: {subject_name_input}")
        print(f"Mark: {subject_mark}")
        print(f"Grade: {individual_grade}")
    else:
        print(f"\nError: Subject '{subject_name_input}' not found for {student_name_input}.")
else:
    print(f"\nError: Student '{student_name_input}' not found in the records.")


--- Individual Subject Grade ---
Student: Bob
Subject: Math
Mark: 75
Grade: B


## Calculate and Display Overall Percentage and Grade

### Subtask:
Compute the student's overall percentage across all subjects by summing up all their marks and dividing by the total possible marks (assuming each subject has a maximum of 100 marks). Then, use the previously defined grading thresholds to determine the student's overall grade (A+, A, B, C, D, or F) and display both the overall percentage and overall grade.

**Reasoning**:
To calculate the overall percentage and grade, I need to access the student's marks from the `student_grades` dictionary, sum them up, calculate the total possible marks, and then apply the grading thresholds. A code block is necessary for these calculations and conditional logic.



In [41]:
if student_name_input in student_grades:
    student_subjects = student_grades[student_name_input]
    total_marks_obtained = sum(student_subjects.values())
    num_subjects = len(student_subjects)
    total_possible_marks = num_subjects * 100

    if num_subjects > 0:
        overall_percentage = (total_marks_obtained / total_possible_marks) * 100
        overall_grade = ''

        if overall_percentage >= grade_aplus:
           overall_grade = 'A+'
        elif overall_percentage >= grade_a:
           overall_grade = 'A'
        elif overall_percentage >= grade_b:
           overall_grade = 'B'
        elif overall_percentage >= grade_c:
           overall_grade = 'C'
        elif overall_percentage >= grade_d:
           overall_grade = 'D'
        else:
           overall_grade = 'F'

        print(f"\n--- Overall Performance ---")
        print(f"Student: {student_name_input}")
        print(f"Total Marks Obtained: {total_marks_obtained}")
        print(f"Overall Percentage: {overall_percentage:.2f}%")
        print(f"Overall Grade: {overall_grade}")
    else:
        print(f"\nError: No subjects found for student '{student_name_input}'.")
else:
    print(f"\nError: Student '{student_name_input}' not found in the records.")


--- Overall Performance ---
Student: Bob
Total Marks Obtained: 255
Overall Percentage: 85.00%
Overall Grade: A


Now, we can update the individual subject grade calculation to use this new function.

In [45]:
if student_name_input in student_grades:
    if subject_name_input in student_grades[student_name_input]:
        subject_mark = student_grades[student_name_input][subject_name_input]
        individual_grade = get_grade(subject_mark)

        print(f"\n--- Individual Subject Grade (Simplified) ---")
        print(f"Student: {student_name_input}")
        print(f"Subject: {subject_name_input}")
        print(f"Mark: {subject_mark}")
        print(f"Grade: {individual_grade}")
    else:
        print(f"\nError: Subject '{subject_name_input}' not found for {student_name_input}.")
else:
    print(f"\nError: Student '{student_name_input}' not found in the records.")


--- Individual Subject Grade (Simplified) ---
Student: Bob
Subject: Math
Mark: 75
Grade: B


And similarly, we can update the overall percentage grade calculation using the same function.

In [44]:
if student_name_input in student_grades:
    student_subjects = student_grades[student_name_input]
    total_marks_obtained = sum(student_subjects.values())
    num_subjects = len(student_subjects)
    total_possible_marks = num_subjects * 100

    if num_subjects > 0:
        overall_percentage = (total_marks_obtained / total_possible_marks) * 100
        overall_grade = get_grade(overall_percentage)

        print(f"\n--- Overall Performance (Simplified) ---")
        print(f"Student: {student_name_input}")
        print(f"Total Marks Obtained: {total_marks_obtained}")
        print(f"Overall Percentage: {overall_percentage:.2f}%")
        print(f"Overall Grade: {overall_grade}")
    else:
        print(f"\nError: No subjects found for student '{student_name_input}'.")
else:
    print(f"\nError: Student '{student_name_input}' not found in the records.")


--- Overall Performance (Simplified) ---
Student: Bob
Total Marks Obtained: 255
Overall Percentage: 85.00%
Overall Grade: A


## Final Task

### Subtask:
Provide a summary of the student's grade for the selected subject and their overall grade, confirming the successful execution of the grading logic.


## Summary:

### Q&A
The student's grade for the selected subject (History for Bob) is A+, based on a mark of 92. The student's overall grade (for Bob) is A, with an overall percentage of 85.00%. The grading logic was successfully executed, calculating both individual subject and overall grades according to the defined thresholds.

### Data Analysis Key Findings
*   A nested dictionary named `student_grades` was successfully created to store student names, subjects, and their corresponding marks (e.g., Alice: Math 90, Science 85, History 78; Bob: Math 75, Science 88, History 92; Charlie: Math 65, Science 70, History 80).
*   Clear grading thresholds were defined: A+ (90%), A (80%), B (70%), C (60%), and D (50%).
*   The system successfully captured user input for the student's name and a specific subject. For the example run, the inputs were 'Bob' and 'History'.
*   For the selected student 'Bob' and subject 'History', the mark of 92 was retrieved, and the individual subject grade was correctly determined as 'A+'.
*   For the student 'Bob', the total marks obtained across all subjects were 255.
*   The overall percentage for 'Bob' was calculated as 85.00% (255 / (3 subjects * 100 max marks)).
*   Based on the overall percentage of 85.00%, the student 'Bob' received an overall grade of 'A'.

### Insights or Next Steps
*   The current grading system effectively calculates individual subject grades and overall performance based on predefined thresholds. This provides a clear and functional framework for student assessment.
*   To enhance the system, consider implementing more robust error handling for cases where a student or subject is not found, or when non-numeric input is provided for marks. Additionally, the system could be extended to allow for dynamic modification of grading thresholds or to support weighted subjects.
